### ISSUE TITLE
Several issues on OpenBSD

### ISSUE THREAD

**Issue by ranrin** [tudurom/disputils#2]
I use cwm. 

1.  lsd, pfd, phd and ppd regularly print strange characters.
2. dattr can't find output output sometimes.
3. pfd cannot get output name for Firefox. (The only one I've encountered so far)

**Comment by tudurom** [comment]
Jesus Christ the strange characters problem is here again...

This should be the root of the other 2 problems. Thanks for reporting!

**Comment by tudurom** [comment]
Strange thing is that I cannot reproduce the issue. I am going to spin up an OpenBSD vm.

**Comment by tudurom** [comment]
@ranrin I pushed a fix, please try it.

**Comment by ranrin** [comment]
@tudurom They work fine now. Although the third issue still persist for Firefox, I haven't been able to reproduce it on an another window.

**Comment by tudurom** [comment]
Do you keep the Firefox window in the corner of the display?

**Comment by ranrin** [comment]
No, not at all but (as an example) wattr seems to think I do. To add this, I'm starting to think this isn't related to disputils.

**Comment by tudurom** [comment]
Also, what do you mean by "pfd cannot get output name for Firefox"? Do you mean that `pfd` cannot find the output name when Firefox is focused?

**Comment by ranrin** [comment]
Yes, that was what I meant.

**Comment by tudurom** [comment]
Pull all the new changes, recompile and try this:

Get the id of the firefox window (`pfw` or `lsw`).

Execute: `pfd -w $wid`.

Tell me the result.

**Comment by ranrin** [comment]
> pfd: Cannot get output name

**Comment by tudurom** [comment]
Run `xrandr`. If one of the displays is named "default" that might be the problem.

**Comment by ranrin** [comment]
This is the output of xrandr:

> Screen 0: minimum 8 x 8, current 4160 x 1080, maximum 32767 x 32767
LVDS1 connected 1600x900+2560+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1600x900      60.11*+
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       59.94  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 connected primary 2560x1080+0+0 (normal left inverted right x axis y axis) 798mm x 334mm
   2560x1080     60.00*+
   1920x1080     60.00    50.00    59.94    30.00    29.97  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1600x900      59.98  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.08    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis

**Comment by tudurom** [comment]
I pushed a possible fix, please try it.

**Comment by ranrin** [comment]
Unfortunately, it had no effect.
